# Generated by Django 5.2.5 on 2025-08-24 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beat',
            name='thumbnail_url',
            field=models.URLField(blank=True),
        ),
    ]
